const PRODUCT_STATUS = {
  ACTIVE: 'ACTIVE',
  ARCHIVED: 'ARCHIVED',
  DRAFT: 'DRAFT',
};

const WEIGHT_UNITS = {
  GRAMS: 'GRAMS',
  KILOGRAMS: 'KILOGRAMS',
  OUNCES: 'OUNCES',
  POUNDS: 'POUNDS',
};

const DEFAULT_LIMITS = {
  PRODUCTS_PER_PAGE: 10,
  MAX_PRODUCTS_PER_PAGE: 100,
  SEARCH_RESULTS: 10,
};

module.exports = {
  PRODUCT_STATUS,
  WEIGHT_UNITS,
  DEFAULT_LIMITS,
};